<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="details.css">
    <script src="https://kit.fontawesome.com/a99a57c334.js" crossorigin="anonymous"></script>
</head>

<body>


    <header class="header">
        <div class="logo">
            <img src="logo.png" alt="Musify">
        </div>
        <nav class="nav">
            <a href="">Home</a>
            <a href="">Genres</a>
            <a href="">Playlists</a>
            <a href="">Log In Register</a>
        </nav>
    </header>

    <div class="search-box">
        <input class="search-txt" type="text" name="" placeholder="Type to search">
        <a class="search-btn" href="#">
            <i class="fa fa-search-plus"></i>
        </a>

    </div>


    
<div class="grid-container">

    <div class="imagen">
        <img src="image.coldplay.jpg" alt="COLDPLAY">
    </div>

    <div class="letras1">

        <h1>Coldplay</h1>

        <p class="tracks">TOP TRACKS</p>

        <ul class="listas">
            <li>Yellow</li>
            <li>The Scientist</li>
            <li>Paradise</li>
            <li>Clocks</li>
            <li>O</li> 
        </ul>

        <p class="albums">TOP ALBUMS</p>

        <ul class="album-box">
            <li>Everyday Life</li>
            <li>Ghost Stories</li>
            <li>A Head Full of Dreams</li>
        </ul>

        </div>

</div>

</body>

</html>

CSS

body{
    background-image: url(img.fondo.jpg);
    background-position: center;
}

.search-box{
    position: absolute;
    top: 13%;
    left: 50%;
    transform: translate(-50%,50%);
    background:white;
    height: 40px;
    border-radius: 40px;
    padding: 10px;
}


.search-btn{
    color:white;
    float: right;
    width: 40px;
    height: 40px;
    border-radius: 50%;
    background-color: rgb(110, 159, 248);
    display: flex;
    justify-content: center;
    align-items: center;
}

.search-txt{
    border: none;
    background: none;
    outline: none;
    float: left;
    padding-left: 3mm;
    color: gray;
    font-size: 16px;
    transition: 0.4s;
    line-height: 37px;
    width: 600px
}

.header{
    background-color: rgb(110, 159, 248);
    color:black;
    display: grid;
    grid-template-columns: 80px 440px;
    gap: 820px;
    text-decoration-color: white;
    height: 100%;
    margin-top: 0.5cm;

}

.logo{
    padding-left: 4mm;
}

.nav {
    display: grid;
    grid-template-columns: 100px 100px 100px 200px;
    margin: 15px;
    gap: 50px;
    font-size: 5mm; 
    padding-top: 2mm;
    font-style: inherit;
    margin-left: 235%;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
}

a{
    text-decoration: none;
    color: white;
}


.grid-container{
display: grid;
box-sizing: border-box;
border: 1px black solid;
gap: 60px;
width: 1700px;
height: 800px;
background-color: rgb(110, 159, 248);
margin-top: 400px;
margin-left: 450px
}

.letras1{
font-size: xx-large;
font-family: Verdana, Geneva, Tahoma, sans-serif;
margin-left: 900px;
margin-bottom: 800px;
float: left;
width: 40%;
position: absolute;
}



.tracks{
    font-size: larger;
    border: black 2px solid;
    background-color: gray;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    width: 77%;
}

.listas{
    gap: 5px;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    font-size: xx-large
}

.albums{
    font-size: larger;
    border: black 2px solid;
    background-color: gray;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    width: 77%;
}

.album-box{
    gap: 5px;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    font-size: xx-large
}

.imagen{

    width: 47%;
    margin-top: 150px;
    margin-left: 30px;
    position: absolute;
}
    
